import reducers from '../redux/rootReducer';

test('reducers', () => {
  const state = reducers({
    cocktails: {
      loading: false,
      cocktails: [{
        idDrink: '17203', strDrink: 'Kir', strDrinkAlternate: null, strTags: 'IBA,ContemporaryClassic', strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Wine Glass', strInstructions: 'Add the crème de cassis to the bottom of the glass, then top up with wine.', strInstructionsES: null, strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.', strInstructionsFR: null, strInstructionsIT: 'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/apneom1504370294.jpg', strIngredient1: 'Creme de Cassis', strIngredient2: 'Champagne', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 part ', strMeasure2: '5 parts ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-02 17:38:14',
      }, {
        idDrink: '12764', strDrink: 'Karsk', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Highball glass', strInstructions: 'Put a copper coin in a coffe-cup and fill up with coffee until you no longer see the coin, then add alcohol until you see the coin. Norwegian speciality.', strInstructionsES: null, strInstructionsDE: 'Legen Sie eine Kupfermünze in eine Kaffeetasse und füllen Sie sie mit Kaffee, bis Sie die Münze nicht mehr sehen, dann fügen Sie Alkohol hinzu, bis Sie die Münze wieder sehen. Norwegische Spezialität.', strInstructionsFR: null, strInstructionsIT: 'Metti una moneta di rame in una tazza da caffè e riempila di caffè finché non vedi più la moneta, quindi aggiungi l\'alcol finché non vedi la moneta. Specialità norvegese.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/808mxk1487602471.jpg', strIngredient1: 'Coffee', strIngredient2: 'Grain alcohol', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 part ', strMeasure2: '2 parts ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-02-20 14:54:31',
      }, {
        idDrink: '11600', strDrink: 'Kamikaze', strDrinkAlternate: null, strTags: 'IBA,NewEra', strVideo: null, strCategory: 'Ordinary Drink', strIBA: 'New Era Drinks', strAlcoholic: 'Alcoholic', strGlass: 'Cocktail glass', strInstructions: 'Shake all ingredients together with ice. Strain into glass, garnish and serve.', strInstructionsES: null, strInstructionsDE: 'Alle Zutaten zusammen mit Eis schütteln. In ein Glas abseihen, garnieren und servieren.', strInstructionsFR: null, strInstructionsIT: 'Shakerare tutti gli ingredienti insieme al ghiaccio.Filtrare nel bicchiere, guarnire e servire.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/d7ff7u1606855412.jpg', strIngredient1: 'Vodka', strIngredient2: 'Triple sec', strIngredient3: 'Lime juice', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 oz ', strMeasure2: '1 oz ', strMeasure3: '1 oz ', strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: 'https://commons.wikimedia.org/wiki/File:Kamikaze-cocktail.jpg', strImageAttribution: 'Bevvy', strCreativeCommonsConfirmed: 'Yes', dateModified: '2017-09-02 18:26:44',
      }, {
        idDrink: '13837', strDrink: 'Kir Royale', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Champagne Flute', strInstructions: 'Pour Creme de cassis in glass, gently pour champagne on top', strInstructionsES: null, strInstructionsDE: 'Creme de Cassis in ein Glas geben, vorsichtig Champagner darüber gießen.', strInstructionsFR: null, strInstructionsIT: 'Versare la Creme de cassis nel bicchiere, versai sopra delicatamente lo champagne', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yt9i7n1504370388.jpg', strIngredient1: 'Creme de Cassis', strIngredient2: 'Champagne', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 part ', strMeasure2: '5 parts ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-02 17:39:48',
      }, {
        idDrink: '14456', strDrink: 'Kurant Tea', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Coffee / Tea', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Champagne flute', strInstructions: 'Pour Absolut Kurant into a comfortably big tea-cup. Add the not too hot(!) apple tea and, if you like, some sugar. Enjoy!', strInstructionsES: null, strInstructionsDE: 'Geben Sie Absolut Kurant in eine bequeme, große Teetasse. Füge den nicht zu heißen(!) Apfeltee und, wenn du willst, etwas Zucker hinzu. Viel Spaß!', strInstructionsFR: null, strInstructionsIT: 'Versare Absolut Kurant in una tazza da tè comodamente grande.\r\nAggiungete il tè alla mela non troppo caldo (!) E, se vi piace, dello zucchero.\r\nGodere!', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xrsrpr1441247464.jpg', strIngredient1: 'Absolut Kurant', strIngredient2: 'Tea', strIngredient3: 'Sugar', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '4 cl ', strMeasure2: 'Turkish apple ', strMeasure3: ' (if needed)\n', strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2015-09-03 03:31:04',
      }, {
        idDrink: '14752', strDrink: 'Kiwi Lemon', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Highball glass', strInstructions: 'Mix in highball glass. Stirr. Garnish with slice of kiwi.', strInstructionsES: null, strInstructionsDE: 'Im Highball-Glas untermischen. Rühren. Mit einer Scheibe Kiwi garnieren.', strInstructionsFR: null, strInstructionsIT: 'Mescolare in un bicchiere highball.\r\nAgitare.\r\nGuarnire con una fetta di kiwi.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tpupvr1478251697.jpg', strIngredient1: 'Kiwi liqueur', strIngredient2: 'Bitter lemon', strIngredient3: 'Ice', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 part ', strMeasure2: '2 parts ', strMeasure3: 'cubes', strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2016-11-04 09:28:17',
      }, {
        idDrink: '16951', strDrink: 'Kioki Coffee', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Coffee / Tea', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Coffee mug', strInstructions: 'Stir. Add whipped cream to the top.', strInstructionsES: null, strInstructionsDE: 'Rühren. Die geschlagene Sahne dazugeben.', strInstructionsFR: null, strInstructionsIT: 'Versare tutti gli ingredienti nel bicchiere. Aggiungere la panna montata in cima. Agitare.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/uppqty1441247374.jpg', strIngredient1: 'Kahlua', strIngredient2: 'Brandy', strIngredient3: 'Coffee', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 oz ', strMeasure2: '1/2 oz ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2015-09-03 03:29:34',
      }, {
        idDrink: '13190', strDrink: 'Kool-Aid Shot', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Shot', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Old-fashioned glass', strInstructions: 'Pour into a large glass with ice and stir. Add a little cranberry juice to taste.', strInstructionsES: null, strInstructionsDE: 'In ein großes Glas mit Eis gießen und umrühren. Nach Belieben etwas Preiselbeersaft hinzufügen.', strInstructionsFR: null, strInstructionsIT: 'Versare in un bicchiere grande con ghiaccio e mescolare.\r\nAggiungere un po \'di succo di mirtillo rosso a piacere.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/fegm621503564966.jpg', strIngredient1: 'Vodka', strIngredient2: 'Amaretto', strIngredient3: 'Sloe gin', strIngredient4: 'Triple sec', strIngredient5: 'Cranberry juice', strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 shot ', strMeasure2: '1 shot ', strMeasure3: '1 shot ', strMeasure4: '1 shot ', strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-08-24 09:56:06',
      }, {
        idDrink: '15026', strDrink: 'Kiss me Quick', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Highball glass', strInstructions: 'mix in the glass', strInstructionsES: null, strInstructionsDE: 'Im Glas mischen.', strInstructionsFR: null, strInstructionsIT: 'Versare tutti gli ingredienti in un bicchiere, mescola bene.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/m7iaxu1504885119.jpg', strIngredient1: 'Cranberry vodka', strIngredient2: 'Apfelkorn', strIngredient3: 'Schweppes Russchian', strIngredient4: 'Apple juice', strIngredient5: 'Ice', strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '4 cl ', strMeasure2: '2 cl ', strMeasure3: '7 cl ', strMeasure4: '8 cl ', strMeasure5: 'cubes', strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-08 16:38:39',
      }, {
        idDrink: '17006', strDrink: 'Kool First Aid', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Shot', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Shot glass', strInstructions: 'Add Kool Aid to a double shot glass, and top with rum. Slam and shoot.', strInstructionsES: null, strInstructionsDE: 'Geben Sie Kool Aid in ein Doppelschnapsglas und füllen Sie es mit Rum. Knall und Schuss.', strInstructionsFR: null, strInstructionsIT: 'Aggiungi Kool-Aid, successivamente aggiungi il rum.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/hfp6sv1503564824.jpg', strIngredient1: '151 proof rum', strIngredient2: 'Kool-Aid', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '2 oz light ', strMeasure2: '1/2 tsp Tropical ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-08-24 09:53:44',
      }, {
        idDrink: '11602', strDrink: 'Kentucky B And B', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Brandy snifter', strInstructions: 'Pour the bourbon and Benedictine into a brandy snifter.', strInstructionsES: null, strInstructionsDE: 'Den Bourbon und den Benediktiner in ein Brandyglas geben.', strInstructionsFR: null, strInstructionsIT: 'Versare il bourbon e il benedettino in un bicchierino di brandy.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/sqxsxp1478820236.jpg', strIngredient1: 'Bourbon', strIngredient2: 'Benedictine', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '2 oz ', strMeasure2: '1/2 oz ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2016-11-10 23:23:56',
      }, {
        idDrink: '11604', strDrink: 'Kentucky Colonel', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Ordinary Drink', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Cocktail glass', strInstructions: 'In a shaker half-filled with ice cubes combine the courbon and Benedictine. Shake and strain into a cocktail glass. Garnish with the lemon twist.', strInstructionsES: null, strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, den Bourbon und den Benediktiner vermengen. Schütteln und in ein Cocktailglas abseihen. Mit der Zitronenscheibe garnieren.', strInstructionsFR: null, strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio unire il courbon e il benedettino.Shakerare e filtrare in una coppetta da cocktail. Guarnire con la scorza di limone.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/utqwpu1478820348.jpg', strIngredient1: 'Bourbon', strIngredient2: 'Benedictine', strIngredient3: 'Lemon peel', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '3 oz ', strMeasure2: '1/2 oz ', strMeasure3: '1 twist of ', strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2016-11-10 23:25:48',
      }, {
        idDrink: '14446', strDrink: 'Kool-Aid Slammer', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Shot', strIBA: null, strAlcoholic: 'Alcoholic', strGlass: 'Shot glass', strInstructions: 'Fill half the shot glass with the kool-aid first. Then put a paper towel over the top of the glass and slowly pour in the vodka. If you do it right, you should be able to see that the two liquids are separated, with the vodka on top. Now slam it! The last thing you\'ll taste is the kool-aid.', strInstructionsES: null, strInstructionsDE: 'Füllen Sie zuerst die Hälfte des Schnapsglases mit dem Kool-Aid. Dann legen Sie ein Papiertuch über das Glas und gießen Sie den Wodka langsam ein. Wenn du es richtig machst, solltest du sehen können, dass die beiden Flüssigkeiten getrennt sind, mit dem Wodka oben drauf. Jetzt knall es rein! Das Letzte, was du schmecken wirst, ist das Kool-Aid.', strInstructionsFR: null, strInstructionsIT: 'Riempi prima metà del bicchierino con il kool-aid.\r\nQuindi mettere un tovagliolo di carta sulla parte superiore del bicchiere e versare lentamente la vodka.\r\nSe lo fai bene, dovresti essere in grado di vedere che i due liquidi sono separati, con la vodka sopra.\r\nOra sbattilo! L\'ultima cosa che assaggerai è il kool-aid.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/kugu2m1504735473.jpg', strIngredient1: 'Kool-Aid', strIngredient2: 'Vodka', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1/2 oz Grape ', strMeasure2: '1/2 oz ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-06 23:04:33',
      }, {
        idDrink: '12714', strDrink: 'Kiwi Papaya Smoothie', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Other/Unknown', strIBA: null, strAlcoholic: 'Non alcoholic', strGlass: 'Highball Glass', strInstructions: 'Throw everything into a blender and liquify.', strInstructionsES: null, strInstructionsDE: 'Alles in einen Mixer geben und aufschlagen.', strInstructionsFR: null, strInstructionsIT: 'Getta tutto in un frullatore e liquida.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jogv4w1487603571.jpg', strIngredient1: 'Kiwi', strIngredient2: 'Papaya', strIngredient3: null, strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '3 ', strMeasure2: '1/2 ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-02-20 15:12:51',
      }, {
        idDrink: '12720', strDrink: 'Kill the cold Smoothie', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Other/Unknown', strIBA: null, strAlcoholic: 'Non alcoholic', strGlass: 'Highball glass', strInstructions: 'Juice ginger and lemon and add it to hot water. You may add cardomom.', strInstructionsES: null, strInstructionsDE: 'Ingwer und Zitrone entsaften und in heißes Wasser geben. Du kannst Cardomom hinzufügen.', strInstructionsFR: null, strInstructionsIT: 'Spremere lo zenzero e il limone e aggiungerlo all\'acqua calda.Puoi aggiungere il cardamomo.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/7j1z2e1487603414.jpg', strIngredient1: 'Ginger', strIngredient2: 'Lemon', strIngredient3: 'Water', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 inch ', strMeasure2: '1/4 ', strMeasure3: '1 cup hot ', strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-02-20 15:10:15',
      }],
      error: '',
    },
    cocktail: { loading: false, cocktail: [], error: '' },
    filter: false,
    query: 't',
  }, {
    type: 'FETCH_COCKTAILS_SUSSESS',
    payload: [{
      idDrink: '17219', strDrink: 'Yellow Bird', strDrinkAlternate: null, strTags: 'IBA,NewEra', strVideo: null, strCategory: 'Cocktail', strIBA: 'New Era Drinks', strAlcoholic: 'Alcoholic', strGlass: 'Cocktail glass', strInstructions: 'Shake and strain into a chilled cocktail glass', strInstructionsES: null, strInstructionsDE: 'In ein gekühltes Cocktailglas schütteln und abseihen.', strInstructionsFR: null, strInstructionsIT: 'Shakerare e filtrare in una coppetta da cocktail ghiacciata', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2t9r6w1504374811.jpg', strIngredient1: 'White Rum', strIngredient2: 'Galliano', strIngredient3: 'Triple Sec', strIngredient4: 'Lime Juice', strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '3 cl', strMeasure2: '1.5 cl', strMeasure3: '1.5 cl', strMeasure4: '1.5 cl', strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-02 18:53:31',
    }, {
      idDrink: '12728', strDrink: 'Yoghurt Cooler', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Other/Unknown', strIBA: null, strAlcoholic: 'Non alcoholic', strGlass: 'Highball Glass', strInstructions: 'Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up. Note: Use lots of ice in this one - great on hot days! To add ice: Remove the center of the cover while the blender is on - drop 3 or 4 ice cubs and blend until they\'re completely crushed.', strInstructionsES: null, strInstructionsDE: 'Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen. Hinweis: Verwenden Sie viel Eis in diesem Gerät - ideal an heißen Tagen! Um Eis hinzuzufügen: Entfernen Sie die Mitte der Abdeckung, während der Mixer eingeschaltet ist - lassen Sie 3 oder 4 Eiswürfel fallen und mischen Sie sie, bis sie vollständig zerkleinert sind.', strInstructionsFR: null, strInstructionsIT: 'Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Nota: usa molto ghiaccio in questo - ottimo nelle giornate calde!Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.Per aggiungere il ghiaccio: rimuovere il centro del coperchio mentre il frullatore è acceso - far cadere 3 o 4 cubetti di ghiaccio e frullare fino a quando non saranno completamente schiacciati.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/trttrv1441254466.jpg', strIngredient1: 'Yoghurt', strIngredient2: 'Fruit', strIngredient3: 'Ice', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 cup ', strMeasure2: '1 cup ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2015-09-03 05:27:46',
    }],
  });
  expect(state).toEqual({
    cocktails: {
      loading: false,
      cocktails: [{
        idDrink: '17219', strDrink: 'Yellow Bird', strDrinkAlternate: null, strTags: 'IBA,NewEra', strVideo: null, strCategory: 'Cocktail', strIBA: 'New Era Drinks', strAlcoholic: 'Alcoholic', strGlass: 'Cocktail glass', strInstructions: 'Shake and strain into a chilled cocktail glass', strInstructionsES: null, strInstructionsDE: 'In ein gekühltes Cocktailglas schütteln und abseihen.', strInstructionsFR: null, strInstructionsIT: 'Shakerare e filtrare in una coppetta da cocktail ghiacciata', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2t9r6w1504374811.jpg', strIngredient1: 'White Rum', strIngredient2: 'Galliano', strIngredient3: 'Triple Sec', strIngredient4: 'Lime Juice', strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '3 cl', strMeasure2: '1.5 cl', strMeasure3: '1.5 cl', strMeasure4: '1.5 cl', strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2017-09-02 18:53:31',
      }, {
        idDrink: '12728', strDrink: 'Yoghurt Cooler', strDrinkAlternate: null, strTags: null, strVideo: null, strCategory: 'Other/Unknown', strIBA: null, strAlcoholic: 'Non alcoholic', strGlass: 'Highball Glass', strInstructions: 'Place all ingredients in the blender jar - cover and whiz on medium speed until well blended. Pour in one tall, 2 medium or 3 small glasses and drink up. Note: Use lots of ice in this one - great on hot days! To add ice: Remove the center of the cover while the blender is on - drop 3 or 4 ice cubs and blend until they\'re completely crushed.', strInstructionsES: null, strInstructionsDE: 'Alle Zutaten in den Mixer geben - abdecken und bei mittlerer Geschwindigkeit schaumig schlagen, bis sie gut vermischt sind. In ein großes, 2 mittlere oder 3 kleine Gläser füllen und geniessen. Hinweis: Verwenden Sie viel Eis in diesem Gerät - ideal an heißen Tagen! Um Eis hinzuzufügen: Entfernen Sie die Mitte der Abdeckung, während der Mixer eingeschaltet ist - lassen Sie 3 oder 4 Eiswürfel fallen und mischen Sie sie, bis sie vollständig zerkleinert sind.', strInstructionsFR: null, strInstructionsIT: 'Mettere tutti gli ingredienti nella caraffa del frullatore - coprire e montare a velocità media fino a quando non sono ben amalgamati.Nota: usa molto ghiaccio in questo - ottimo nelle giornate calde!Versare in un bicchiere alto, 2 medi o 3 piccoli e bere.Per aggiungere il ghiaccio: rimuovere il centro del coperchio mentre il frullatore è acceso - far cadere 3 o 4 cubetti di ghiaccio e frullare fino a quando non saranno completamente schiacciati.', 'strInstructionsZH-HANS': null, 'strInstructionsZH-HANT': null, strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/trttrv1441254466.jpg', strIngredient1: 'Yoghurt', strIngredient2: 'Fruit', strIngredient3: 'Ice', strIngredient4: null, strIngredient5: null, strIngredient6: null, strIngredient7: null, strIngredient8: null, strIngredient9: null, strIngredient10: null, strIngredient11: null, strIngredient12: null, strIngredient13: null, strIngredient14: null, strIngredient15: null, strMeasure1: '1 cup ', strMeasure2: '1 cup ', strMeasure3: null, strMeasure4: null, strMeasure5: null, strMeasure6: null, strMeasure7: null, strMeasure8: null, strMeasure9: null, strMeasure10: null, strMeasure11: null, strMeasure12: null, strMeasure13: null, strMeasure14: null, strMeasure15: null, strImageSource: null, strImageAttribution: null, strCreativeCommonsConfirmed: 'No', dateModified: '2015-09-03 05:27:46',
      }],
      error: '',
    },
    cocktail: { loading: false, cocktail: [], error: '' },
    filter: false,
    query: 't',
  });
});
